using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Osm.Data.PBF
{
    /// <summary>
    /// An object that implements this interface can consume objects generated by the PBFReader.
    /// </summary>
    public interface IPBFPrimitiveBlockConsumer
    {
        /// <summary>
        /// Processes a primitive block of OSM data.
        /// </summary>
        /// <param name="block"></param>
        void ProcessPrimitiveBlock(PrimitiveBlock block);
    }
}